import {company,defaults,cases} from './data.mjs';
import {calculate} from './model.mjs';
import {documents} from './diligence-data.mjs';
import {fillRiteAnalysis,spxAnalysis} from './transactions.mjs';

const base=calculate(),plan=calculate({usePlan:true});
const fmt=(v,d=1)=>new Intl.NumberFormat('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
const pct=v=>v==null?'Unavailable':fmt(v*100)+'%';
const cash=v=>'$'+fmt(v)+'m';
const variants={
  base:{label:'At the assumed price',tag:'10× entry · 9× exit',patch:{},question:'Do the assumed terms work?',finding:'The assumed price is the constraint.',detail:'Cash generation pays down debt, but the baseline return remains below the 20% hurdle. This is a conditional scenario result; it does not establish market value or an executable purchase price.'},
  plan:{label:'Add the operating plan',tag:'Pricing · yield · inventory',patch:{usePlan:true},question:'Can operations close the gap?',finding:'An operating plan helps. It does not close the gap.',detail:'Pricing, process yield and inventory initiatives improve modeled cash flow after implementation costs. At the same entry price, the return still misses the hurdle.'},
  downside:{label:'Stress the business',tag:'Demand decline · 7× exit',patch:{caseName:'Downside',exitMultiple:cases.Downside.exitMultiple},question:'What happens in a downturn?',finding:'The downside puts equity at risk.',detail:'Lower demand, compressed margins and a lower exit multiple turn the return negative. These are specified stresses, not probability estimates.'},
  price:{label:'Solve for the bid',tag:fmt(base.maxBidMultiple,2)+'× entry · fixed debt',patch:{entryMultiple:base.maxBidMultiple},question:'What price meets the return target?',finding:'Price discipline changes the decision.',detail:'The model solves for the entry enterprise value that earns 20% IRR while holding the baseline operating case, debt dollars and exit assumptions fixed. It is a conditional bid ceiling, not a market quote.'}
};
const primary=(text='FY2025 Form 10-K')=>`<a href="${documents.annual.url}" target="_blank" rel="noopener noreferrer">${text} ↗</a>`;
function returnGraphic(){
  const rows=[['Baseline',base.irr,'#aec4d7'],['With operating plan',plan.irr,'#a8cdbb'],['Assumed hurdle',defaults.hurdle,'#e7cf9d']];
  return `<svg class="study-return-chart" viewBox="0 0 440 224" role="img" aria-label="Baseline equity IRR ${pct(base.irr)}, with operating plan ${pct(plan.irr)}, versus a 20 percent assumed hurdle.">${rows.map(([label,value,color],i)=>`<text x="0" y="${24+i*72}" fill="#c7d4de" font-size="13">${label}</text><text x="440" y="${24+i*72}" text-anchor="end" fill="#fff" font-size="18">${pct(value)}</text><rect x="0" y="${38+i*72}" width="440" height="8" fill="#ffffff15"/><rect x="0" y="${38+i*72}" width="${value/.25*440}" height="8" fill="${color}"/>`).join('')}</svg>`;
}
function cashGraphic(r){
  const max=Math.max(1,...r.years.map(y=>Math.abs(y.fcf))),width=540,left=12,step=104,baseline=98;
  return `<svg class="study-cash-chart" viewBox="0 0 ${width} 192" role="img" aria-label="Modeled annual free cash flow before principal payments: ${r.years.map(y=>y.year+' '+cash(y.fcf)).join(', ')}"><line x1="8" y1="${baseline}" x2="530" y2="${baseline}" stroke="#b9c7c4"/>${r.years.map((y,i)=>{const height=Math.abs(y.fcf)/max*55,x=left+i*step;return `<rect x="${x+16}" y="${y.fcf>=0?baseline-height:baseline}" width="65" height="${Math.max(1,height)}" fill="${y.fcf>=0?'#2d665b':'#a55b4c'}"/><text x="${x+48}" y="${y.fcf>=0?baseline-height-10:baseline+height+16}" text-anchor="middle" font-size="14" fill="#19392f">${fmt(y.fcf)}</text><text x="${x+48}" y="186" text-anchor="middle" font-size="12" fill="#59685f">${y.year}E</text>`;}).join('')}</svg>`;
}
export function initCaseStudy(onSelect,onInspect){
  const host=document.getElementById('case-study');
  host.innerHTML=`
    <div class="study-hero">
      <div class="study-hero-copy"><p class="study-kicker">INDEPENDENT INVESTMENT CASE / 01</p><h1>Gorman-Rupp.<br><em>Underwriting an<br>industrial buyout.</em></h1><p class="study-deck">Can operating improvements justify the acquisition price? A public-data investment case connecting cash flow, capital structure and manufacturing economics.</p><div class="study-hero-actions"><a class="study-button" href="#financial-model">Explore the live model <span aria-hidden="true">↗</span></a><a class="study-text-link" href="#research">Read the investment memo →</a></div><div class="study-byline"><span>Adam Skarre</span><span>Investment analysis & operating strategy</span></div></div>
      <aside class="study-verdict"><div class="study-card-label"><span>BASELINE FINDING</span><span>01 / PRICE DISCIPLINE</span></div><h2>Good cash flow.<br>A demanding price.</h2><p>At the assumed 10× entry multiple, the deal falls short of the return target—even with the operating plan.</p>${returnGraphic()}<div class="study-bid"><div><span>Entry multiple at 20% IRR</span><strong>${fmt(base.maxBidMultiple,2)}×</strong></div><div><span>Conditional enterprise value</span><strong>${cash(base.maxBid)}</strong></div></div><p class="study-fine">Five-year hold · 4.5× initial debt · 9× exit. Hypothetical transaction terms; gross sponsor returns.</p></aside>
    </div>
    <dl class="study-project-meta"><div><dt>PROJECT TYPE</dt><dd>Independent buyout case study</dd></div><div><dt>ANALYTICAL SCOPE</dt><dd>Research · valuation · operations</dd></div><div><dt>FINANCIAL BASIS</dt><dd>2023–2025 audited history</dd></div><div><dt>BUILT WITH</dt><dd>Live financial model · sourced evidence</dd></div></dl>
    <section class="study-research-feature"><div><p class="study-kicker">TRANSACTION EVIDENCE</p><h2>Before choosing a multiple,<br>reconcile what it measures.</h2><p>Fill-Rite: ${fmt(fillRiteAnalysis().grossMultiple,2)}× gross versus ${fmt(fillRiteAnalysis().adjustedMultiple,2)}× after expected tax benefits. SPX FLOW: ${fmt(spxAnalysis().reportedMultiple,2)}× reported trailing EBITDA versus approximately ${fmt(spxAnalysis().postSynergyMultiple,2)}× on an implied forward, post-synergy basis.</p><a class="study-button" href="#deal-evidence">Explore the actual acquisitions ↗</a></div><div><strong>Three real transactions.<br>Five primary disclosures.</strong><p>Inspect the source figures, challenge add-backs and tax-benefit credit, and identify missing inputs. These conventions provide research context; they do not validate the hypothetical 10× entry or 9× exit used here.</p></div></section>

    <section class="study-section study-question"><div><p class="study-kicker">01 / THE INVESTMENT QUESTION</p><h2>How much is the cash<br>generation worth?</h2></div><div><p>Gorman-Rupp provides a concrete industrial business through which to examine a buyout: product economics, working capital and capital expenditure all affect the cash available to repay debt.</p><p>The project asks whether a five-year acquisition can meet a 20% equity return hurdle, and whether pricing, process yield and inventory improvements change the answer.</p><div class="study-fact-row"><div><strong>${cash(company.revenue)}</strong><span>FY2025 revenue</span></div><div><strong>${cash(company.ebitda)}</strong><span>Operating EBITDA proxy¹</span></div><div><strong>${cash(company.cfo-company.capex)}</strong><span>Reported CFO less capex¹</span></div></div><p class="study-source">${primary('Source: audited financial statements')} · ¹ Derived metrics; definitions and reconciliations are in the model.</p></div></section>

    <section class="study-section"><div class="study-section-heading"><div><p class="study-kicker">02 / THE INVESTMENT JUDGMENT</p><h2>Three findings that shape the bid.</h2></div><button class="study-text-link" data-open-sheet="history">Inspect the financial evidence ↗</button></div><div class="study-findings">
      <article><span class="study-number">01</span><div><p class="study-label">CASH QUALITY</p><h3>Start with the cash bridge.</h3><p>FY2025 reported operating cash flow was ${cash(company.cfo)}. The reconciliation includes a $10.3m deferred-tax adjustment. A single strong cash-flow year is insufficient evidence for a perpetual run rate.</p><p class="study-implication"><b>Underwriting decision</b> Rebuild forecast cash flow from operating earnings, taxes, reinvestment and working capital.</p>${primary('Cash-flow statement, p.31')}</div></article>
      <article><span class="study-number">02</span><div><p class="study-label">EARNINGS DISCIPLINE</p><h3>Keep the EBITDA definition consistent.</h3><p>The model uses ${cash(company.ebitda)} of operating income plus D&A. Management’s adjusted EBITDA uses a different bridge. Applying adjustments without reconciling the definitions can overstate debt capacity and value.</p><p class="study-implication"><b>Underwriting decision</b> Retain the operating proxy and inspect each proposed adjustment separately.</p><button class="study-text-link" data-open-sheet="history">Open the EBITDA reconciliation ↗</button></div></article>
      <article><span class="study-number">03</span><div><p class="study-label">OPERATING VALUE</p><h3>Improvement does not rescue every price.</h3><p>The modeled operating plan increases equity IRR from ${pct(base.irr)} to ${pct(plan.irr)}. That remains below the 20% hurdle after implementation costs and additional capital expenditure.</p><p class="study-implication"><b>Underwriting decision</b> Reprice the transaction; do not rely on unproven operational upside to justify the original bid.</p><a href="#operations">Inspect initiative economics ↗</a></div></article>
    </div></section>

    <section class="study-section study-experiment" aria-labelledby="study-experiment-title"><div class="study-section-heading"><div><p class="study-kicker">03 / CHALLENGE THE CONCLUSION</p><h2 id="study-experiment-title">Change the case.<br>See the decision change.</h2></div><p>These controls run the same financial model used in the detailed worksheets.</p></div><div class="study-experiment-layout"><div class="study-scenarios" role="group" aria-label="Explore investment cases">${Object.entries(variants).map(([id,v],i)=>`<button data-study-case="${id}" aria-pressed="false"><span class="study-scenario-number">0${i+1}</span><span><strong>${v.label}</strong><small>${v.tag}</small></span><span aria-hidden="true">↗</span></button>`).join('')}</div><div id="study-live-result" aria-live="polite"></div></div></section>

    <section class="study-section study-method"><div><p class="study-kicker">04 / HOW THE CASE WAS BUILT</p><h2>From filing<br>to investment decision.</h2><p class="study-section-intro">The work connects three disciplines: financial statement analysis, transaction modeling and an operating plan with explicit cash costs.</p><a class="study-text-link" href="https://github.com/Adam-Skarre/adamskarre.com/tree/main/finance" target="_blank" rel="noopener noreferrer">Review the source code ↗</a></div><ol><li><span>01</span><div><h3>Reconcile the reported business</h3><p>Three years of audited statements, a net-income-to-cash bridge, debt principal reconciliation and a separate LTM update.</p></div></li><li><span>02</span><div><h3>Build the transaction economics</h3><p>Sources and uses, a five-year operating forecast, debt amortization and cash sweeps, liquidity tests, equity returns and a DCF cross-check.</p></div></li><li><span>03</span><div><h3>Quantify the operating hypotheses</h3><p>Pricing net of volume loss, process savings net of cost, and inventory releases treated as working-capital cash—not EBITDA.</p></div></li><li><span>04</span><div><h3>Test the recommendation</h3><p>Downside scenarios, return sensitivities and a solved bid ceiling. Formula traces expose how each forecast output is calculated.</p></div></li></ol></section>

    <section class="study-section study-next"><div><p class="study-kicker">05 / WHAT WOULD CHANGE THE CONCLUSION?</p><h2>The next questions<br>are business questions.</h2></div><div class="study-next-grid"><article><h3>Customer economics</h3><p>Would price increases hold after discounts, churn and competitive responses?</p></article><article><h3>Manufacturing evidence</h3><p>Can product-level scrap and rework data substantiate the proposed yield savings?</p></article><article><h3>Inventory service levels</h3><p>Can cash be released without increasing stockouts or missing delivery commitments?</p></article><article><h3>Financing terms</h3><p>Would lenders support the modeled leverage, covenants and downside liquidity?</p></article></div></section>

    <section class="study-close"><div><p class="study-kicker">EXPLORE THE WORK</p><h2>Read the judgment.<br>Audit the calculations.</h2><p>This is an independent portfolio project using public financial information. Acquisition terms and operating initiatives are assumptions. It does not represent an actual mandate, transaction or measured company improvement.</p></div><div class="study-deliverables"><a href="#financial-model"><span>01</span><div><strong>Financial model</strong><small>Cash flow, debt schedules & formula traces</small></div><b aria-hidden="true">↗</b></a><a href="#research"><span>02</span><div><strong>Investment memo</strong><small>Thesis, recommendation & material risks</small></div><b aria-hidden="true">↗</b></a><a href="#screening"><span>03</span><div><strong>Industry research</strong><small>Five companies, definitions & exceptions</small></div><b aria-hidden="true">↗</b></a><button data-open-sheet="evidence"><span>04</span><div><strong>Evidence & limitations</strong><small>Primary sources and unverified assumptions</small></div><b aria-hidden="true">↗</b></button></div></section>`;
  host.addEventListener('click',event=>{
    const choice=event.target.closest('[data-study-case]');
    if(choice){onSelect({...defaults,...variants[choice.dataset.studyCase].patch});return;}
    const inspect=event.target.closest('[data-open-sheet]');
    if(inspect)onInspect(inspect.dataset.openSheet);
  });
}
export function renderCaseStudy(r){
  const selected=Object.entries(variants).find(([,v])=>Object.entries({...defaults,...v.patch}).every(([key,value])=>Array.isArray(value)?JSON.stringify(value)===JSON.stringify(r.a[key]):typeof value==='number'?Math.abs(r.a[key]-value)<1e-8:r.a[key]===value));
  const id=selected?.[0],variant=selected?.[1];
  document.querySelectorAll('[data-study-case]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.studyCase===id)));
  const title=variant?.finding||(r.feasible?'Your edited assumptions, recalculated.':'The current financing has an unfunded shortfall.');
  const detail=variant?.detail||(r.feasible?'The overview is showing the custom case from the model. The original research conclusion above remains tied to the documented baseline.':'IRR and MOIC are unavailable until the model can fund minimum liquidity. Inspect the debt worksheet before interpreting returns.');
  document.getElementById('study-live-result').innerHTML=`<p class="study-label">${variant?.question||'CUSTOM INVESTMENT CASE'}</p><h3>${title}</h3><p>${detail}</p><div class="study-live-metrics"><div><span>Equity IRR</span><strong data-study-irr>${pct(r.irr)}</strong></div><div><span>Entry enterprise value</span><strong>${cash(r.entryEV)}</strong></div><div><span>Illustrative credit tests</span><strong class="study-credit">${r.creditPass?'Pass':'Fail'}</strong></div></div><div class="study-chart-label"><strong>Cash available before principal payments</strong><span>USD millions · modeled</span></div>${cashGraphic(r)}<a href="#financial-model" class="study-text-link">Trace these cash flows in the model →</a>`;
}
