import {company,cases} from './data.mjs';
import {calculate} from './model.mjs';
import {documents,annuals,cashFlowFacts,interim,endMarkets,earningsBridge,debtFacts,diligenceQuestions} from './diligence-data.mjs';
import {cashRows,traceCalculation,historicalAudit,trailingFinancials,stressCases,debtCapacity,requiredExitMultiple,initiativeAttribution} from './analysis.mjs';

const n=(v,d=1)=>v==null||!Number.isFinite(v)?'n.a.':Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const p=v=>v==null?'n.a.':n(v*100)+'%';
const x=v=>v==null?'n.a.':n(v,2)+'×';
const m=v=>v==null?'n.a.':'$'+n(v)+'m';
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(key,label)=>`<a href="${documents[key].url}" target="_blank" rel="noopener noreferrer">${label||documents[key].title} ↗</a>`;
let pane='cashflow',key='fcf',year=0,lastResult,changeState,exportCase;
const panes={cashflow:'Cash flow & formulas',history:'Reported financials',credit:'Debt & downside',valuation:'Valuation',evidence:'Evidence & diligence'};
const table=(headers,rows,cls='')=>`<div class="table-wrap"><table class="model-table ${cls}"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr class="${row.total?'model-total':''}"><th scope="row">${row.label}</th>${row.values.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const title=(label,caption)=>`<div class="model-panel-heading"><h3>${label}</h3>${caption?`<span>${caption}</span>`:''}</div>`;
function cashflow(r){
  const trace=traceCalculation(r,key,year),audit=historicalAudit(),fy=r.years[0];
  const rows=cashRows.map((row,i)=>`${row.group?`<tr class="model-group"><th colspan="6">${row.group}</th></tr>`:''}<tr class="${row.total?'model-total':''}"><th scope="row">${row.label}</th>${r.years.map((y,j)=>`<td><button class="model-cell ${key===row.key&&year===j?'selected':''}" data-trace="${row.key}" data-year="${j}" aria-label="Inspect ${row.label}, ${y.year}: ${n(y[row.key],3)} million dollars">${n(y[row.key]*(row.sign||1),2)}</button></td>`).join('')}</tr>`).join('');
  return `<article class="model-sheet">${title('The cash-flow model','USD millions · deductions shown as negative values')}<div class="model-help">Click any forecast number to see the calculation. All five years recalculate from the selected investment case.</div><div class="table-wrap"><table class="model-table cashflow-sheet"><thead><tr><th scope="col">Operating forecast & cash conversion</th>${r.years.map(y=>`<th scope="col">${y.year}E</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div></article>
    <aside class="formula-inspector" aria-live="polite"><div class="formula-title"><span class="eyebrow">CALCULATION INSPECTOR</span><strong>${trace.year} · ${e(trace.label)}</strong></div><div class="formula-expression">${e(trace.formula)}</div><div class="formula-substitution">${e(trace.substitution)} <strong>= ${n(trace.value,3)}</strong></div><p>${e(trace.note)}</p><div class="formula-source">Historical starting point: ${link('annual','10-K, pp.29–31')} · Future operating and financing inputs: assumptions</div></aside>
    <div class="model-lead-stats"><div><span>2025 reported operating cash flow</span><strong>${m(company.cfo)}</strong><small>Audited 10-K · cash-flow statement</small></div><div><span>2026 modeled FCF before principal</span><strong>${m(fy.fcf)}</strong><small>After interest, cash taxes & reinvestment</small></div><div><span>5-year cash available before principal</span><strong>${m(r.years.reduce((s,y)=>s+y.fcf,0))}</strong><small>${r.feasible?'No unfunded annual shortfall':'Funding gap — inspect debt & downside'}</small></div></div>
    <div class="model-two"><article class="model-sheet">${title('Why reported CFO is not the LBO cash flow')}<p>Reported FY2025 CFO of ${m(company.cfo)} reflects the existing capital structure, noncash adjustments and actual liability movements. The acquisition forecast rebuilds cash flow with new debt, a cash-tax assumption, recurring capex, and operating working capital.</p><div class="model-equation">${n(fy.ebitda,3)} EBITDA − ${n(fy.interest,3)} interest − ${n(fy.taxes,3)} tax − ${n(fy.capex,3)} capex − ${n(fy.deltaNwc,3)} ΔNWC = <strong>${n(fy.fcf,3)} FCF</strong></div></article><article class="model-sheet">${title('Reconciliation checks','USD millions; unrounded tolerance 0.000001')}${table(['Check','Difference'],[{label:'Sources − uses',values:[n(r.sourceCheck,6)]},{label:'Largest forecast cash roll-forward residual',values:[n(Math.max(...r.years.map(y=>Math.abs(y.cashCheck))),6)]},{label:'Largest debt roll-forward residual',values:[n(Math.max(...r.years.map(y=>Math.abs(y.debtCheck))),6)]},{label:'Equity attribution residual',values:[n(r.bridgeCheck,6)]},{label:'Largest audited historical CFO residual',values:[n(Math.max(...audit.map(y=>Math.abs(y.cfoCheck))),6)]}])}</article></div>`;
}
function historical(){
  const ltm=trailingFinancials(),audit=historicalAudit();
  const annualRows=[['Revenue','revenue'],['Operating income','ebit'],['Depreciation & amortization','da'],['Operating EBITDA proxy',a=>a.ebit+a.da],['Operating EBITDA margin',a=>(a.ebit+a.da)/a.revenue,p],['Reported operating cash flow','cfo'],['Gross capital expenditure','capex'],['Reported CFO − gross capex',a=>a.cfo-a.capex],['FCF / operating EBITDA',a=>(a.cfo-a.capex)/(a.ebit+a.da),p]].map(([label,k,format=n])=>({label,values:annuals.map(a=>format(typeof k==='function'?k(a):a[k]))}));
  const ltmRows=[['Revenue','revenue'],['Operating income','ebit'],['D&A','da'],['Operating cash flow','cfo'],['Capital expenditure','capex']].map(([label,k])=>({label,values:[n(annuals[2][k],3),n(interim.h125[k],3),n(interim.h126[k],3),n(ltm[k],3)]}));
  return `<div class="model-source-ribbon"><strong>Audited annual statements, not a synthetic dataset.</strong><span>2023–2025 history from the FY2025 10-K. USD thousands converted to millions.</span>${link('annual')}</div>
    <article class="model-sheet">${title('Three years of reported performance','A = audited; ratios and FCF are derived')}${table(['USD millions','2023A','2024A','2025A'],annualRows)}</article>
    <article class="model-sheet">${title('Reconcile net income to operating cash flow','Cash-flow statement signs; pp.31')}${table(['Reported reconciliation item','2023A','2024A','2025A'],[...cashFlowFacts.map(([label,values])=>({label,values:values.map(v=>n(v,3))})),{label:'Sum of reported operating items',values:audit.map(a=>n(a.cfo,3)),total:true},{label:'Reported CFO',values:annuals.map(a=>n(a.cfo,3)),total:true},{label:'Reconciliation difference',values:audit.map(a=>n(a.cfoCheck,6))}])}<p class="model-caption">The tax adjustment and liability movements are shown individually. They are not assumed to repeat indefinitely. Cash-flow changes can differ from simple balance-sheet movements because of FX, noncash items and reclassifications.</p></article>
    <div class="model-two"><article class="model-sheet">${title('Cash balance roll-forward','Audited statement of cash flows')}${table(['USD millions','2023A','2024A','2025A'],[['Opening cash','openingCash'],['Operating cash flow','cfo'],['Investing cash flow','investing'],['Financing cash flow','financing'],['FX effect','fx'],['Closing cash','cash']].map(([label,k])=>({label,values:annuals.map(a=>n(a[k],3))})).concat([{label:'Unexplained difference',values:audit.map(a=>n(a.cashCheck,6)),total:true}]))}</article><article class="model-sheet">${title('EBITDA definitions are not interchangeable')}${table(['FY2025 reconciliation','USD m'],earningsBridge.map(row=>({label:row.label,values:[n(row.value,3)],total:row.type==='subtotal'})))}<p class="model-caption">The LBO uses $123.072m operating EBITDA. The pension adjustment is part of management’s net-income-based bridge; adding it blindly to operating EBITDA risks double counting. ${link('earnings','View management reconciliation')}</p></article></div>
    <article class="model-sheet">${title('Update check: LTM to June 2026','FY2025 − H1 2025 + H1 2026')}${table(['USD millions','FY2025A','Less H1 2025U','Add H1 2026U','LTM derived'],ltmRows)}<div class="model-inline-metrics"><span>LTM operating EBITDA <strong>${m(ltm.ebitda)}</strong></span><span>LTM CFO − capex <strong>${m(ltm.fcf)}</strong></span></div><p class="model-caption">U = unaudited interim. The LTM column is an arithmetic bridge, not an audited annual statement. The acquisition model deliberately retains its FY2025 base; this update provides a separate freshness check. ${link('interim')}</p></article>
    <article class="model-sheet">${title('End-market underwriting','FY2025 10-K, Note 2')}${table(['Sales, USD millions','2023A','2024A','2025A','2025 growth','2025 mix'],endMarkets.map(s=>({label:s.name,values:[...s.sales.map(v=>n(v)),p(s.sales[2]/s.sales[1]-1),p(s.sales[2]/company.revenue)]})))}<p class="model-caption">“Repair parts” is a reported sales category. It is not a measure of contracted recurring revenue or all aftermarket activity. Forecast growth and margins remain assumptions until a defensible end-market and pricing bridge is available.</p></article>`;
}
function credit(r){
  const capacity=debtCapacity(r.a),stress=stressCases(r.a);
  const rows=[['Opening term debt','openingTerm'],['Mandatory principal payment','mandatory'],['Excess cash swept to term loan','termSweep'],['Closing term debt','term'],['Opening revolver','openingRevolver'],['New revolver draws','draw'],['Revolver repayments','revolverRepay'],['Closing revolver','revolver'],['Closing cash','cash'],['Unfunded liquidity shortfall','shortfall']];
  return `<div class="model-lead-stats"><div><span>Selected acquisition debt</span><strong>${m(r.initialDebt)}</strong><small>${x(r.a.debtMultiple)} × operating EBITDA</small></div><div><span>Indicative capacity under these tests</span><strong>${capacity?m(capacity.debt):'No feasible debt'}</strong><small>${capacity?x(capacity.multiple)+' EBITDA · selected operating case':'Adjust price or operating assumptions'}</small></div><div><span>Minimum interest coverage</span><strong>${r.minCoverage===null?'No interest':x(r.minCoverage)}</strong><small>${x(r.a.minCoverage)} illustrative minimum</small></div></div>
    <article class="model-sheet">${title('Annual financing waterfall','USD millions')}${table(['Debt & liquidity',...r.years.map(y=>y.year+'E')],rows.map(([label,k])=>({label,values:r.years.map(y=>n(y[k],2)),total:['term','revolver','shortfall'].includes(k)})))}<p class="model-caption">Mandatory amortization → revolver repayment → term-loan sweep → excess cash retained. Interest uses opening balances. The annual model does not establish intra-quarter liquidity or a lender commitment.</p></article>
    <article class="model-sheet">${title('Debt service and covenant headroom','Illustrative acquisition tests')}${table(['Measure',...r.years.map(y=>y.year+'E')],[{label:'EBITDA / cash interest',values:r.years.map(y=>x(y.coverage))},{label:'Coverage headroom above minimum',values:r.years.map(y=>y.coverage===null?'No interest':x(y.coverage-r.a.minCoverage))},{label:'Year-end net debt / EBITDA',values:r.years.map(y=>x(y.netLeverage))},{label:'Net leverage headroom below maximum',values:r.years.map(y=>y.netLeverage===null?'n.a.':x(r.a.maxLeverage-y.netLeverage))},{label:'Cash available / mandatory principal',values:r.years.map(y=>y.mandatory>0?x(y.fcf/y.mandatory):'No amortization')},{label:'Undrawn revolver',values:r.years.map(y=>m(r.a.revolverLimit-y.revolver))}])}</article>
    <article class="model-sheet">${title('Does the financing survive a downturn?','Shocks apply to every forecast year')}${table(['Stress relative to current case','Growth shift','Margin shift','Interest shift','Equity IRR','Min. coverage','Peak cash shortfall','Credit tests'],stress.map(s=>({label:s.name,values:[n(s.growth*100)+' pp',n(s.margin*100)+' pp',n(s.rate*100)+' pp',s.result?p(s.result.irr):'Out of bounds',s.result?x(s.result.minCoverage):'—',s.result?m(Math.max(...s.result.years.map(y=>y.shortfall))):'—',s.result?(s.result.creditPass?'Pass':'Fail'):'—']})))}<p class="model-caption">These are deterministic sensitivities, not estimated probabilities. Debt capacity is the largest feasible debt on a 0.01× grid from 0× to 8×, subject to positive sponsor equity, minimum cash, revolver capacity, interest coverage, and entry / annual net-leverage tests. It is not a market financing quote.</p></article>
    <div class="model-two"><article class="model-sheet">${title('Actual debt is different from the hypothetical buyout')}${table(['FY2025 debt note','USD m'],[{label:'Senior secured term principal',values:[n(debtFacts.term,3)]},{label:'6.40% notes principal',values:[n(debtFacts.notes,3)]},{label:'Total principal',values:[n(debtFacts.principal,3)],total:true},{label:'Less unamortized fees / discount',values:[n(-debtFacts.unamortizedFees,3)]},{label:'Balance-sheet carrying value',values:[n(debtFacts.carryingValue,3)],total:true}])}<p class="model-caption">Actual year-end senior rate: 5.8%; actual revolving facility: $100m. The illustrative acquisition assumes a new structure. ${link('annual','Note 4, pp.40–41')}</p></article><article class="model-sheet">${title('Do not mistake a screen for a covenant opinion')}<p>The reported senior agreement steps to a 3.50× net leverage ceiling and requires at least 3.00× interest coverage. Definitions and adjustments follow the agreement.</p><p>The buyout model instead uses ${x(r.a.maxLeverage)} maximum net leverage and ${x(r.a.minCoverage)} coverage with the operating EBITDA proxy. Passing those hypothetical tests does not establish compliance with the company’s existing agreement.</p><p class="model-caption">Pension and postretirement liabilities total ${m(debtFacts.pension+debtFacts.postretirement)} before any funding, tax or transaction adjustments. No debt-like adjustment is silently embedded in the price.</p></article></div>`;
}
function valuation(r){
  const last=r.years.at(-1),required=requiredExitMultiple(r),roic=r.a.terminalRoic;
  const rates=[.08,.09,.10,.11,.12],growth=[.01,.02,.025,.03];
  const cells=rates.map(w=>({label:p(w)+' WACC',values:growth.map(g=>`<button class="model-cell" data-wacc="${w}" data-terminal="${g}" aria-label="Apply ${p(w)} WACC and ${p(g)} terminal growth">${m(calculate({...r.a,wacc:w,terminalGrowth:g}).dcfEV)}</button>`)}));
  const attribution=initiativeAttribution(r.a);
  return `<div class="model-lead-stats"><div><span>Purchase price at target IRR</span><strong>${r.feasible?m(r.maxBid):'Unavailable'}</strong><small>${x(r.maxBidMultiple)} × current operating EBITDA</small></div><div><span>DCF enterprise value</span><strong>${m(r.dcfEV)}</strong><small>${p(r.a.wacc)} WACC · ${p(r.a.terminalGrowth)} growth · ${p(roic)} terminal ROIC</small></div><div><span>Exit multiple needed at this entry price</span><strong>${x(required)}</strong><small>To earn ${p(r.a.hurdle)} IRR; selected exit ${x(r.a.exitMultiple)}</small></div></div>
    <article class="model-sheet">${title('Discount the cash, then fund sustainable growth','USD millions')}${table(['DCF calculation',...r.years.map(y=>y.year+'E')],[{label:'Unlevered free cash flow',values:r.years.map(y=>n(y.ufcf,3))},{label:'Discount factor',values:r.years.map((y,i)=>n(1/Math.pow(1+r.a.wacc,i+1),4))},{label:'Present value',values:r.years.map((y,i)=>n(y.ufcf/Math.pow(1+r.a.wacc,i+1),3)),total:true}])}<div class="model-two terminal-details"><div>${table(['Terminal calculation','USD m'],[{label:'Normalized terminal NOPAT',values:[n(r.terminalNopat,3)]},{label:`Reinvestment = NOPAT × ${p(r.a.terminalGrowth)} / ${p(roic)}`,values:[n(r.terminalReinvestment,3)]},{label:'Terminal FCFF = NOPAT − reinvestment',values:[n(r.terminalFcf,3)],total:true},{label:'Terminal value = FCFF / (WACC − growth)',values:[n(r.terminalFcf/(r.a.wacc-r.a.terminalGrowth),3)]},{label:'PV of terminal value',values:[n(r.pvTerminal,3)]},{label:'PV of explicit forecast',values:[n(r.pvForecast,3)]},{label:'Enterprise value',values:[n(r.dcfEV,3)],total:true}])}</div><div><h3>Terminal growth has a cost.</h3><p>Reinvestment consumes ${p(r.a.terminalGrowth/roic)} of positive terminal operating profit after tax. Terminal value represents ${p(r.terminalShare)} of the DCF.</p><p>Terminal ROIC is an assumption about returns on future reinvestment. It is not a reported company metric. Historical D&A / sales provides the normalized terminal depreciation estimate; acquisition accounting is excluded.</p><label class="model-standalone-input">Terminal ROIC (%)<input data-model-param="terminalRoic" data-scale="100" type="number" min="1" max="50" step=".5" value="${roic*100}"></label><p class="model-caption">${link('terminal','Why growth and reinvestment must be linked')}</p></div></div></article>
    <article class="model-sheet">${title('DCF sensitivity','Click a value to apply WACC and terminal growth')}${table(['Enterprise value',...growth.map(g=>p(g)+' growth')],cells)}<p class="model-caption">Terminal ROIC remains ${p(roic)}. Discount rates and growth rates are assumed; no market-derived WACC or quoted valuation is represented.</p></article>
    <article class="model-sheet">${title('From enterprise value to sponsor returns','Actual cash-flow endpoints in this model')}${table(['Calculation','Substitution','Result'],[{label:'Exit enterprise value',values:[`${n(last.recurringEbitda,3)} EBITDA × ${x(r.a.exitMultiple)}`,m(r.exitEV)]},{label:'Exit equity',values:[`${n(r.exitEV,3)} EV − ${n(r.exitCosts,3)} fees − ${n(last.term+last.revolver,3)} debt + ${n(last.cash,3)} cash`,m(r.exitEquity)]},{label:'MOIC',values:[`${n(r.exitEquity,3)} / ${n(r.sponsorEquity,3)}`,x(r.moic)]},{label:'Annual equity IRR',values:[`MOIC^(1 / 5) − 1`,p(r.irr)],total:true}])}<p class="model-caption">No interim distributions or equity rescue contributions. Returns are gross of fund fees and carry. If financing cannot fund minimum liquidity, IRR and MOIC are unavailable.</p></article>
    <article class="model-sheet">${title('Operating initiative attribution','Incremental exit equity, net of modeled costs and financing effects')}${attribution?table(['Initiative','Allocated exit equity contribution'],[...attribution.contributions.map(c=>({label:c.label,values:[m(c.value)]})),{label:'Combined plan vs. all initiatives off',values:[m(attribution.uplift)],total:true},{label:'Allocation reconciliation',values:[n(attribution.check,6)]}]):'<p>Attribution is unavailable because at least one initiative combination has an unfunded cash shortfall.</p>'}<p class="model-caption">The allocation averages marginal contributions across all six possible initiative sequences. This gives an order-independent allocation of interacting modeled cash flows; it is not causal evidence that the initiatives will work. Disabled initiatives receive zero. Edit the hypotheses in Value creation.</p></article>`;
}
function evidence(r){
  const tests=historicalAudit();
  return `<div class="model-source-ribbon"><strong>Evidence standard</strong><span>Reported figures, derived calculations and forward assumptions remain separate. Research checked September 23, 2026.</span></div>
    <article class="model-sheet">${title('Investment question and disconfirming evidence')}<p class="model-thesis">Can an industrial pump business generate enough recurring cash to justify the purchase price while funding reinvestment and surviving a cyclical downturn?</p><div class="model-two"><div><h3>What supports further work</h3><ul><li>Reported revenue spans eight end-market categories, with a visible repair-parts contribution.</li><li>Three audited years permit an earnings-to-cash reconciliation.</li><li>The operating plan exposes pricing, process costs and inventory as separate hypotheses.</li></ul></div><div><h3>What could invalidate the thesis</h3><ul><li>A valuation that only works with aggressive add-backs, perpetual margin gains, or exit multiple expansion.</li><li>Tax timing, LIFO accounting or liability movements mistaken for recurring cash generation.</li><li>Financing terms or implementation costs that make the downside unfundable.</li></ul></div></div><p class="model-caption">At the selected terms, modeled equity IRR is ${p(r.irr)} versus a ${p(r.a.hurdle)} hurdle. A passing return calculation is a condition for further diligence, not an investment approval.</p></article>
    <article class="model-sheet">${title('Diligence agenda: evidence → test → decision')}${table(['Issue','Observed evidence','Work needed','Underwriting consequence'],diligenceQuestions.map(q=>({label:q.issue,values:[e(q.evidence)+'<br>'+link(q.source,'Source'),e(q.test),e(q.decision)]})),'diligence-table')}</article>
    <article class="model-sheet">${title('Source register','Open the underlying primary material')}${table(['Document','Period / date','Status','Location'],Object.entries(documents).map(([k,d])=>({label:link(k),values:[d.period||'Methodology',d.assurance,d.locations]})),'diligence-table')}<p class="model-caption">Methods references inform the structure of the analysis. They do not validate this company thesis, these assumptions, or the author’s qualifications.</p></article>
    <article class="model-sheet">${title('Assumption register','Changes propagate to every connected view')}${table(['Assumption','Current setting','Basis'],[{label:'Entry / exit EV / EBITDA',values:[x(r.a.entryMultiple)+' / '+x(r.a.exitMultiple),'Illustrative transaction terms; no observed deal multiple']},{label:'Initial leverage / interest',values:[x(r.a.debtMultiple)+' / '+p(r.a.interestRate),'Hypothetical new financing; no commitment']},{label:'Operating case',values:[r.a.caseName,'Independent scenario; not management guidance']},{label:'Recurring capex / sales',values:[p(r.a.capexRatio),'Underwriting assumption; historical capex shown separately']},{label:'Cash tax rate',values:[p(r.a.taxRate),'Simplified positive pretax income tax']},{label:'Operating NWC / sales',values:[p(r.a.nwcRatio),'FY2025 operating balance-sheet proxy']},{label:'WACC / terminal growth / terminal ROIC',values:[p(r.a.wacc)+' / '+p(r.a.terminalGrowth)+' / '+p(r.a.terminalRoic),'Sensitivity inputs; not empirically estimated']},{label:'Initiatives',values:[r.a.usePlan?'Included':'Excluded','Unverified hypotheses with explicit ramp, cost and capex']}])}</article>
    <article class="model-sheet">${title('Known limits of the case')}<p>This is an annual cash-flow buyout model with financing schedules. It is not a full purchase-accounting or integrated three-statement model, a quality-of-earnings opinion, a lender underwriting package, or a completed investment.</p><p>It omits intrayear revolver timing, commitment fees, NOLs and tax-interest limitations, stock versus asset acquisition tax effects, restricted cash, acquisition accounting, fund fees and carry, and a market-validated control premium. Public financials cannot replace customer diligence, a management plan, or lender terms.</p><p class="model-caption">These are material limits on interpretation. They are visible so a reviewer can judge the model rather than infer unavailable evidence.</p></article>`;
}
export function renderWorkbench(r){
  lastResult=r;const host=document.getElementById('financial-model');if(!host)return;
  const controlsOpen=host.querySelector('.model-control-disclosure')?.open??false;
  const controls=[['entryMultiple','Entry multiple',1,2,25,.1],['debtMultiple','Debt / EBITDA',1,0,8,.1],['interestRate','Interest (%)',100,.1,30,.1],['capexRatio','Capex / sales (%)',100,0,20,.1],['taxRate','Cash tax (%)',100,0,50,.5]];
  host.innerHTML=`<div class="workbench-heading"><div><p class="eyebrow">ACQUISITION UNDERWRITING / MODEL WORKBOOK</p><h2>Follow the cash. Inspect the assumptions.</h2><p>Audited financial history → operating forecast → debt repayment → equity returns.</p></div><button class="button secondary" data-model-export>Export current case</button></div><nav class="model-tabs" aria-label="Financial model worksheets">${Object.entries(panes).map(([id,label])=>`<button data-model-pane="${id}" aria-pressed="${pane===id}">${label}</button>`).join('')}</nav><details class="model-control-disclosure" ${controlsOpen?'open':''}><summary>Edit purchase price, financing & cash-flow assumptions</summary><div class="model-input-bar">${controls.map(([k,label,scale,min,max,step])=>`<label>${label}<input data-model-param="${k}" data-scale="${scale}" type="number" min="${min}" max="${max}" step="any" value="${Number((r.a[k]*scale).toFixed(6))}"></label>`).join('')}<label>Operating case<select data-model-case>${Object.keys(cases).map(name=>`<option ${name===r.a.caseName?'selected':''}>${name}</option>`).join('')}</select></label></div></details><div class="model-status-line"><span>${r.a.caseName} case · ${r.a.usePlan?'Operating initiatives on':'Operating initiatives off'} · USD millions</span><span>Historical: sourced · Forecast: assumed · Cells: calculated</span></div><p class="model-input-error" role="alert" hidden>Complete all inputs with numbers inside the stated limits.</p><div id="model-worksheet">${({cashflow,history:historical,credit,valuation,evidence}[pane])(r)}</div>`;
}
export function initWorkbench(onChange,onExport){
  changeState=onChange;exportCase=onExport;const host=document.getElementById('financial-model');
  host.addEventListener('click',event=>{
    const target=event.target.closest('button');if(!target)return;
    if(target.dataset.modelPane){pane=target.dataset.modelPane;renderWorkbench(lastResult);}
    else if(target.dataset.trace){key=target.dataset.trace;year=Number(target.dataset.year);renderWorkbench(lastResult);document.querySelector('.formula-inspector')?.scrollIntoView?.({block:'nearest',behavior:'smooth'});}
    else if(target.dataset.wacc){changeState({wacc:Number(target.dataset.wacc),terminalGrowth:Number(target.dataset.terminal)});}
    else if(target.hasAttribute('data-model-export'))exportCase();
  });
  const validate=()=>{const invalid=[...host.querySelectorAll('[data-model-param]')].some(el=>el.value===''||!el.checkValidity());host.querySelector('.model-input-error').hidden=!invalid;host.querySelector('#model-worksheet').hidden=invalid;return !invalid;};
  host.addEventListener('input',event=>{if(event.target.dataset.modelParam)validate();});
  host.addEventListener('change',event=>{
    const el=event.target;
    if(el.hasAttribute('data-model-case')){changeState({caseName:el.value,exitMultiple:cases[el.value].exitMultiple});return;}
    if(!el.dataset.modelParam)return;
    if(!validate()){el.setAttribute('aria-invalid','true');el.reportValidity();return;}
    el.removeAttribute('aria-invalid');changeState(Object.fromEntries([...host.querySelectorAll('[data-model-param]')].map(input=>[input.dataset.modelParam,Number(input.value)/Number(input.dataset.scale||1)])));
  });
}
